import { Travel } from "models/travel";

const travelLists = [
  new Travel("beijing", "China - Beijing"),
  new Travel("bangkok", "Thailand - Bangkok"),
  new Travel("pataya", "Thailand - Pataya"),
  new Travel("cebu", "Philippines - Cebu"),
  new Travel("tokyo", "Japan - Tokyo"),
  new Travel("rotenburg", "Germany - Rotenburg"),
  new Travel("munchen", "Germany - München"),
  new Travel("salzburg", "Austria - Salzburg"),
  new Travel("salzgammergut", "Austria - Salzgammergut"),
  new Travel("hallstatt", "Austria - Hallstatt"),
  new Travel("vienna", "Austria - Vienna"),
  new Travel("praha", "Czech - Praha"),
  new Travel("bamberg", "Germany - Bamberg"),
  new Travel("wurzburg", "Germany - Würzburg"),
  new Travel("astana", "Kazahstan - Astana"),
  new Travel("danang", "Viet Nam - Danang"),
  new Travel("hue", "Viet Nam - Hue"),
  new Travel("hoian", "Viet Nam - Hoi an"),
  new Travel("jangjiajie", "China - Jangjiajie"),
  new Travel("osaka", "Japan - Osaka"),
  new Travel("kyoto", "Japan - Kyoto"),
  new Travel("paris", "France - Paris"),
  new Travel("luzern", "Swiss - Luzern"),
  new Travel("alphs", "Swiss - Alphs"),
  new Travel("venezia", "Italy - Venezia"),
  new Travel("firenze", "Italy - Firenze"),
  new Travel("amalfi", "Italy - Amalfi"),
  new Travel("vatican", "Vatican"),
  new Travel("roma", "Italy - Roma"),
];

export default travelLists;
